name             'email'
maintainer       'Maxim Filatov'
maintainer_email 'pipopolam@gmail.com'
license          'MIT'
description      'Installs/Configures postfix and opendkim with multidomain support'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.0.1'
depends          'apt'
depends          'yum'
supports         'ubuntu'
supports         'debian'
supports         'centos'
